server:
  port: 9999

bot:
  telegram:
    token: ${BOT_TOKEN}

springdoc:
  swagger-ui:
    path: swagger-ui

kafka:
  serverUrl: ${KAFKA_SERVER_URL:localhost:9092}
  topicName: ${KAFKA_TOPIC_NAME:TelegramUpdate}
  isEnabled: true