server:
  port: 9999

service:
  emailUrl: ${EMAIL_URL:http://localhost:8080}

bot:
  telegram:
    token: ${BOT_TOKEN}

springdoc:
  swagger-ui:
    path: swagger-ui

kafka:
  serverUrl: ${KAFKA_SERVER_URL:localhost:9092}
  groupId: ${KAFKA_MESSAGE_GROUP_ID:"letter_message"}
  topicName: ${KAFKA_TOPIC_NAME:TelegramUpdate}
  isEnabled: true

http:
  controller:
    isEnabled: true