server:
  port: 9090

springdoc:
  swagger-ui:
    path: "/swagger-ui"

vk:
  bot:
    config:
      token: ${BOT_TOKEN}
      groupId: 220038078
      callback:
        confirmationCode: ${SERVER_RESPONSE}
        secret: ${SECRET}